### ISSUE TITLE
add multithreading for the ZK prover and verifcation

### ISSUE THREAD

**Issue by omershlo** [KZen-networks/class-groups#21]
There are two loops, one in `prove` function and one in `verify` function. I tried Rayon (Dependency still there) but I got a memory error from PARI.

**Comment by omershlo** [comment]
example :https://github.com/KZen-networks/zk-paillier/blob/master/src/zkproofs/range_proof.rs#L180

**Comment by amanusk** [comment]
In #20, running tests in parallel also causes PARI memory issues, could be related.
